### ISSUE TITLE
Auto-Generate AdditionalAssemblyInfo.cs file for InternalsVisibleTo

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-Windows#329] opened 2022-12-06 19:24 UTC
### Describe the bug

From #326 and the PR to fix it in #327 we figured out how to generate AssemblyMetadata attributes as part of the MSBuild project to not have to have so many `AssemblyInfo.cs` files in our projects.

We can use this approach for `InternalVisibleTo` as well and remove the `AdditionalAssemblyInfo.cs` files in the library projects.

Related to #321

### Steps to reproduce

```text
N/A
```

### Expected behavior

Less extraneous files to worry about and copy

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Help us help you

Yes, but only if others can assist.

**Comment by Arlodotexe** [comment] 2022-12-09 23:00
@michael-hawker This is a duplicate of #320

**Closed by Arlodotexe** 2022-12-09 23:00 UTC
Labels: enhancement, testing 🏗, templating, source generator :gear:

**Comment by michael-hawker** [comment] 2022-12-09 23:25
Ah, missed you had filed one already.
